# Generated by Django 6.0.6 on 2026-07-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Rukmini', max_length=100)),
                ('role_title', models.CharField(default='Full-Stack Django Developer', help_text='Shown as the eyebrow label in the hero section.', max_length=150)),
                ('headline', models.CharField(default='Building products layer by layer.', help_text='Main hero heading. Wrap the word you want highlighted in **double asterisks**.', max_length=200)),
                ('intro', models.TextField(default="I'm Rukmini — a B.Tech CS student who designs and ships complete web applications end-to-end: Django backends, REST APIs, and interfaces people actually enjoy using.")),
                ('about_heading', models.CharField(default='I like building things that go from a blank Django project to something a real user can log into.', max_length=250)),
                ('about_body', models.TextField(default="I'm currently pursuing my B.Tech in Computer Science & IT at Ajay Kumar Garg Engineering College, Ghaziabad (2023–2027). Outside coursework, I build full production-style Django applications module by module — custom user roles, JWT authentication, REST APIs, and dashboards that update in real time.")),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resume/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('github_url', models.URLField(blank=True, default='https://github.com/rukmini12438')),
                ('linkedin_url', models.URLField(blank=True, default='https://www.linkedin.com/in/rukmini-96b005287')),
                ('leetcode_url', models.URLField(blank=True, default='https://leetcode.com/u/Rukmini2025')),
                ('grad_year', models.CharField(default='2027', max_length=20)),
                ('leetcode_count', models.CharField(default='200+', max_length=20)),
            ],
            options={
                'verbose_name': 'Profile (hero & about content)',
                'verbose_name_plural': 'Profile (hero & about content)',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TimelineEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_label', models.CharField(help_text="e.g. '2023 — 2027' or 'Ongoing'", max_length=60)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Timeline entries',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField(blank=True, help_text='Optional explanatory text shown under the category title — use this for System Design to explain what it covers.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('skills', models.ManyToManyField(blank=True, related_name='skill_categories', to='portfolio.tag')),
            ],
            options={
                'verbose_name_plural': 'Skill categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('live', 'Live build'), ('progress', 'In progress'), ('archived', 'Archived')], default='live', max_length=20)),
                ('short_description', models.TextField()),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('github_url', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='projects', to='portfolio.tag')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
    ]
